from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth', '0012_alter_user_first_name_max_length')]
    operations = [
        migrations.CreateModel(name='Categoria',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('nombre',models.CharField(max_length=80,unique=True))]),
        migrations.CreateModel(name='Evento',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('titulo',models.CharField(max_length=150)),('fecha',models.DateField()),('hora',models.TimeField(blank=True,null=True)),('categoria',models.CharField(blank=True,max_length=80)),('descripcion',models.TextField(blank=True))]),
        migrations.CreateModel(name='Curso',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('nombre',models.CharField(max_length=80,unique=True)),('jornada',models.CharField(blank=True,max_length=30)),('activo',models.BooleanField(default=True)),('profesor',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='cursos_asignados',to='auth.user'))]),
        migrations.CreateModel(name='Perfil',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('rol',models.CharField(choices=[('ADMIN','Administrador'),('PROF','Profesor')],default='PROF',max_length=10)),('usuario',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='perfil',to='auth.user'))]),
        migrations.CreateModel(name='Estudiante',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('rut',models.CharField(max_length=12,unique=True)),('nombres',models.CharField(max_length=100)),('apellidos',models.CharField(max_length=100)),('activo',models.BooleanField(default=True)),('curso',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='estudiantes',to='core.curso'))]),
        migrations.CreateModel(name='Producto',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('codigo',models.CharField(max_length=30,unique=True)),('nombre',models.CharField(max_length=120)),('stock',models.PositiveIntegerField(default=0)),('stock_minimo',models.PositiveIntegerField(default=1)),('estado',models.CharField(choices=[('OK','Disponible'),('BAJO','Stock bajo'),('MANT','Mantención'),('BAJA','Dado de baja')],default='OK',max_length=10)),('ubicacion',models.CharField(blank=True,max_length=120)),('categoria',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='productos',to='core.categoria'))]),
        migrations.CreateModel(name='Asistencia',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('fecha',models.DateField()),('estado',models.CharField(choices=[('P','Presente'),('A','Ausente'),('J','Justificado'),('T','Atraso')],default='P',max_length=1)),('observacion',models.CharField(blank=True,max_length=200)),('estudiante',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='asistencias',to='core.estudiante')),('registrado_por',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to='auth.user'))],options={'ordering':['-fecha','estudiante__apellidos']}),
        migrations.AddConstraint(model_name='asistencia',constraint=models.UniqueConstraint(fields=('estudiante','fecha'),name='uniq_asistencia_estudiante_fecha')),
    ]
